/**
 * Purpose: Guobiao-aligned fan lexicon entries by registry id.
 * Description:
 * - Static copy for result UI; keys match FAN_REGISTRY.
 * - Text is a condensed paraphrase of 《中国麻将竞赛规则》番种表;
 *   authoritative wording is the official published rulebook.
 */
export const FAN_LEXICON_ENTRIES = Object.freeze({
  MEN_QIAN_QING: "门前清：和牌时未进行过吃、碰或明杠，进张均为自摸。",
  ZI_MO: "自摸：和牌牌张为自己摸入，而非他人打出。",
  QI_DUI: "七对：由七个对子组成的特殊和型，计 24 番。",
  SHI_SAN_YAO: "十三幺：十三种幺九字各一张加其中一对作将，计 88 番。",
  GANG_SHANG_HUA: "杠上开花：开杠后摸到的补牌即和牌，计 8 番。",
  HAI_DI_LAO_YUE: "海底捞月：摸完牌墙最后一张牌自摸和牌，计 8 番。",
  HE_DI_LAO_YU: "河底捞鱼：他人打出全桌最后一张牌点和，计 8 番。",
  QING_YI_SE: "清一色：和牌仅含一种序数花色，计 24 番。",
  HUN_YI_SE: "混一色：和牌仅一种序数花色加字牌，计 6 番。",
  DUAN_YAO: "断幺：和牌无幺九牌与字牌，计 2 番。",
  PENG_PENG_HU: "碰碰和：四组面子均为刻子（杠），计 6 番。",
  HUN_YAO_JIU: "混幺九：由幺九与字牌组成的特殊组合型，计 32 番。",
  ZI_YI_SE: "字一色：和牌全部为字牌，计 64 番。",
  QING_YAO_JIU: "清幺九：和牌全部为幺九序数牌，计 64 番。",
  QING_LONG: "清龙：同一花色 1—9 各出现一次的顺子组合，计 16 番。",
  PING_HU: "平和：四组顺子加一对将，且非自摸门清将非幺九，计 2 番。",
  YI_BAN_GAO: "一般高：两组完全相同的顺子，计 1 番。",
  SAN_SE_SAN_TONG_SHUN: "三色三同顺：三种花色各一组相同点数顺子，计 8 番。",
  MEN_FENG_KE: "门风刻：与自己座位门风相同的字刻，计 2 番。",
  QUAN_FENG_KE: "圈风刻：与当前圈风相同的字刻，计 2 番。",
  DA_SI_XI: "大四喜：东南西北四风字均为刻子或杠，计 88 番。",
  XIAO_SI_XI: "小四喜：三风刻加剩余一风作将，计 64 番。",
  DA_SAN_YUAN: "大三元：中发白均为刻子或杠，计 88 番。",
  XIAO_SAN_YUAN: "小三元：两箭刻加剩余箭牌作将，计 64 番。",
  HUA_LONG: "花龙：三种花色各一条 1—9 顺子相连成龙形，计 8 番。",
  XI_XIANG_FENG: "喜相逢：两种花色两组同数顺子，计 1 番。",
  LIAN_LIU: "连六：一种花色两组相连六张顺子，计 1 番。",
  LAO_SHAO_FU: "老少副：同时含 123 与 789 序数顺子，计 1 番。",
  QUE_YI_MEN: "缺一门：和牌缺一种序数花色，计 1 番。",
  WU_ZI: "无字：和牌无字牌，计 1 番。",
  SAN_SE_SAN_BU_GAO: "三色三步高：三色顺子点数依次递增一位，计 6 番。",
  YI_SE_SAN_BU_GAO: "一色三步高：同色三组顺子点数依次递增一位，计 16 番。",
  DA_YU_WU: "大于五：和牌仅由序数 6—9 组成，计 12 番。",
  XIAO_YU_WU: "小于五：和牌仅由序数 1—4 组成，计 12 番。",
  QUAN_DA: "全大：和牌序数牌均为 7—9，计 24 番。",
  QUAN_XIAO: "全小：和牌序数牌均为 1—3，计 24 番。",
  QUAN_ZHONG: "全中：和牌序数牌均为 4—6，计 24 番。",
  DA_SAN_FENG: "大三风：三种风字刻（或杠）加余下一风作将，计 12 番。",
  SHUANG_JIAN_KE: "双箭刻：中发白中两组为刻或杠，计 6 番。",
  SHUANG_TONG_KE: "双同刻：两种花色两组同点数刻子，计 2 番。",
  SAN_TONG_KE: "三同刻：三种花色三组同点数刻子，计 16 番。",
  LV_YI_SE: "绿一色：和牌仅由绿色系牌组成，计 88 番。",
  JIU_LIAN_BAO_DENG: "九莲宝灯：同色 1112345678999 型听九面，计 88 番。",
  SI_GANG: "四杠：和牌含四组杠，计 88 番。",
  QI_LIAN_DUI: "连七对：同色连续七个对子，计 88 番。",
  SI_AN_KE: "四暗刻：四组暗刻/暗杠加一对将，计 64 番。",
  YI_SE_SHUANG_LONG_HUI: "一色双龙会：同色两组老少副且同数将，计 64 番。",
  YI_SE_SI_TONG_SHUN: "一色四同顺：同色四组完全相同顺子，计 48 番。",
  YI_SE_SI_BU_GAO: "一色四步高：同色四组顺子点数依次递增，计 32 番。",
  SAN_GANG: "三杠：和牌含三组杠，计 32 番。",
  QI_XING_BU_KAO: "七星不靠：十三张不靠加七字，计 24 番。",
  QUAN_SHUANG_KE: "全双刻：刻子点数均为 2、4、6、8，计 24 番。",
  YI_SE_SAN_TONG_SHUN: "一色三同顺：同色三组完全相同顺子，计 24 番。",
  YI_SE_SAN_JIE_GAO: "一色三节高：同色三组刻子点数依次递增一，计 24 番。",
  SHANG_SAN_PAI: "序数上档和：判定序数偏七至九侧时计 24 番（与「全大」牌型番不同）。",
  ZHONG_SAN_PAI: "序数中档和：判定序数偏四至六侧时计 24 番（与「全中」牌型番不同）。",
  XIA_SAN_PAI: "序数下档和：判定序数偏一至三侧时计 24 番（与「全小」牌型番不同）。",
  SAN_SE_YI_TONG_SHUN: "三色一通顺：三色各一顺且首尾相连成 123—789 型，计 8 番。",
  TUI_BU_DAO: "推不倒：和牌仅由筒条中可倒置仍合法的牌组成，计 8 番。",
  SAN_SE_SAN_JIE_GAO: "三色三节高：三色刻子点数依次递增一，计 8 番。",
  WU_FAN_HE: "无番和：和牌不计任何其它番种时计 8 番。",
  QIANG_GANG_HU: "抢杠和：他人补杠时抢和该张，计 8 番。",
  SHUANG_AN_GANG: "双暗杠：两组暗杠，计 8 番。",
  QUAN_DAI_WU: "全带五：每组面子均含序数 5，计 16 番。",
  SAN_AN_KE: "三暗刻：三组暗刻，计 16 番。",
  WU_MEN_QI: "五门齐：万筒条字均有，计 6 番。",
  QUAN_QIU_REN: "全求人：副露后点和最后一张，计 6 番。",
  SHUANG_MING_GANG: "双明杠：两组明杠，计 4 番。",
  QUAN_DAI_YAO: "全带幺：每组顺刻杠及将均含幺九，计 4 番。",
  BU_QIU_REN: "不求人：无点和且无私杠，计 4 番。",
  AN_GANG: "暗杠：四张同牌暗扣成杠，计 2 番。",
  MING_GANG: "明杠：明面杠，计 1 番。",
  JUE_ZHANG: "和绝张：所和牌为该类牌的最后一次出现，计 4 番。",
  JIAN_KE: "箭刻：中发白字刻或杠，计 2 番。",
  YAO_JIU_KE: "幺九刻：幺九序数或风字刻/杠，计 1 番。",
  BIAN_ZHANG: "边张：听 12 胡 3 或听 89 胡 7 的边张和，计 1 番。",
  KAN_ZHANG: "坎张：听两面夹张之一成和，计 1 番。",
  DAN_DIAO_JIANG: "单钓将：仅听一张作将成和，计 1 番。",
  HUA_PAI: "花牌：每花 1 番，不计入 14 张；在和牌条件中填花数。",
  SHUANG_AN_KE: "双暗刻：两组暗刻，计 2 番。",
  SAN_SE_SHUANG_LONG_HUI: "三色双龙会：三色两组老少副且 5 作将，计 16 番。",
});
