import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import {
  deployScriptPath,
  getSandboxChildEnv,
  prepareDeploySandbox,
  rootDir,
  today
} from "../helpers/deploySandbox.js";

function runInSandbox(sandboxRoot, ...args) {
  return spawnSync(process.execPath, [join("scripts", "deploy.js"), ...args], {
    cwd: sandboxRoot,
    encoding: "utf8",
    env: getSandboxChildEnv(sandboxRoot)
  });
}

test("deploy CLI prints normalized usage for invalid mode", () => {
  const run = spawnSync(process.execPath, [deployScriptPath, "bad-mode"], {
    cwd: rootDir,
    encoding: "utf8"
  });
  assert.equal(run.status, 1);
  assert.match(
    run.stderr,
    /npm run deploy -- major\|minor\|patch\|build\|release\|doctor/
  );
});

test("deploy CLI prints embedded changelog update prompt template", () => {
  const sandboxRoot = prepareDeploySandbox();
  const changelogPath = join(sandboxRoot, "CHANGELOG.md");
  const before = readFileSync(changelogPath, "utf8");
  const run = runInSandbox(sandboxRoot, "prompt-update");
  const after = readFileSync(changelogPath, "utf8");
  rmSync(sandboxRoot, { recursive: true, force: true });
  assert.equal(run.status, 0);
  assert.match(run.stdout, /\[Unreleased\]/);
  assert.match(run.stdout, /Added \/ Changed \/ Fixed/);
  assert.match(run.stdout, /npm test/);
  assert.notEqual(after, before);
  assert.match(after, /Prompt update generated by deploy script/);
});

test("deploy CLI prints embedded changelog release prompt template", () => {
  const sandboxRoot = prepareDeploySandbox();
  const changelogPath = join(sandboxRoot, "CHANGELOG.md");
  const before = readFileSync(changelogPath, "utf8");
  const run = runInSandbox(sandboxRoot, "prompt-release");
  const after = readFileSync(changelogPath, "utf8");
  rmSync(sandboxRoot, { recursive: true, force: true });
  assert.equal(run.status, 0);
  assert.match(run.stdout, /package\.json/);
  assert.match(run.stdout, /src\/config\/appVersion\.js/);
  assert.match(run.stdout, /\[Unreleased\]/);
  assert.match(run.stdout, /今天日期/);
  assert.notEqual(after, before);
  assert.match(after, /^## \[Unreleased\]\n/m);
  assert.match(after, new RegExp(`^## \\[0\\.4\\.0\\] - ${today}$`, "m"));
});

test("deploy CLI prints both prompt templates with prompt-all mode", () => {
  const sandboxRoot = prepareDeploySandbox();
  const changelogPath = join(sandboxRoot, "CHANGELOG.md");
  const before = readFileSync(changelogPath, "utf8");
  const run = runInSandbox(sandboxRoot, "prompt-all");
  const after = readFileSync(changelogPath, "utf8");
  rmSync(sandboxRoot, { recursive: true, force: true });
  assert.equal(run.status, 0);
  assert.match(run.stdout, /=== prompt-update ===/);
  assert.match(run.stdout, /=== prompt-release ===/);
  assert.match(run.stdout, /Added \/ Changed \/ Fixed/);
  assert.match(run.stdout, /package\.json/);
  assert.notEqual(after, before);
  assert.match(after, /^## \[Unreleased\]\n/m);
  assert.match(after, new RegExp(`^## \\[0\\.4\\.0\\] - ${today}$`, "m"));
});

test("deploy CLI prints cursor agent pipeline command for update prompt", () => {
  const sandboxRoot = prepareDeploySandbox();
  const changelogPath = join(sandboxRoot, "CHANGELOG.md");
  const before = readFileSync(changelogPath, "utf8");
  const run = runInSandbox(sandboxRoot, "prompt-update-agent");
  const after = readFileSync(changelogPath, "utf8");
  rmSync(sandboxRoot, { recursive: true, force: true });
  assert.equal(run.status, 0);
  assert.match(run.stdout, /cursor agent --print --mode ask/);
  assert.match(run.stdout, /CHANGELOG\.md 的 \[Unreleased\]/);
  assert.notEqual(after, before);
  assert.match(after, /Prompt update generated by deploy script/);
});

test("deploy CLI prints cursor agent pipeline command for release prompt", () => {
  const sandboxRoot = prepareDeploySandbox();
  const changelogPath = join(sandboxRoot, "CHANGELOG.md");
  const before = readFileSync(changelogPath, "utf8");
  const run = runInSandbox(sandboxRoot, "prompt-release-agent");
  const after = readFileSync(changelogPath, "utf8");
  rmSync(sandboxRoot, { recursive: true, force: true });
  assert.equal(run.status, 0);
  assert.match(run.stdout, /cursor agent --print --mode ask/);
  assert.match(run.stdout, /准备发布/);
  assert.notEqual(after, before);
  assert.match(after, /^## \[Unreleased\]\n/m);
  assert.match(after, new RegExp(`^## \\[0\\.4\\.0\\] - ${today}$`, "m"));
});
